name: CD (Frontend)

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/cd-frontend.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/package.json
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload assets
        uses: actions/upload-pages-artifact@v5
        with:
          path: frontend/build/client

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
